### ISSUE TITLE
stop using wofi

### ISSUE THREAD

**Issue by electron271** [corrosionwm/corrosionwm#18]
![image](https://user-images.githubusercontent.com/66094410/227631967-65f6eabb-0845-4696-9aca-838ef0d7349d.png)

as wofi is no longer actively maintained, using it may not be a great idea

**Comment by electron271** [comment]
https://github.com/natpen/awesome-wayland#launchers

out of these yofi and fuzzel look like interesting ones to use

**Comment by a-weeb-programmer** [comment]
we need to remove the hardcoded keybind that executes wofi altogether

We have a config parser now, we need to use it so that the user can make their own binds

**Comment by Henry-Hiles** [comment]
This isn't a bug and in my opinion should not have the bug label.

**Comment by electron271** [comment]
iirc the launcher is configurable now, i have tested this
