### ISSUE TITLE
support for other programming languages to configure corrosionwm

### ISSUE THREAD

**Issue by electron271** [corrosionwm/corrosionwm#24]
in the future letting you configure corrosionwm with other languages (e.g. lua, shell script, or a custom lang) may be a good idea in the future

**Comment by a-weeb-programmer** [comment]
Making this would be hell, and it seems kinda extraneous. Configs really just store data for the program to parse, so it would be counterproductive to make it parse multiple config formats when it'll still collect the same key-value pairs but in different languages.

**Comment by electron271** [comment]
yeah i personally agree with this

**Comment by GenShibe** [comment]
> Making this would be hell, and it seems kinda extraneous. Configs really just store data for the program to parse, so it would be counterproductive to make it parse multiple config formats when it'll still collect the same key-value pairs but in different languages.

ASTRIDDDDDD YOU'RE ALIVEEEEE
